FROM realite/python3.6
COPY ./tasks_proj /tmp/tasks_proj
RUN pip3 install -U pytest &&\
	pip3 install /tmp/tasks_proj &&\
	rm -rf /tmp/tasks_proj &&\
	mkdir tasks_db

# PyTest测试实战环境
# tasks list 有错误提示